### ISSUE TITLE
Question: plugins property empty

### ISSUE THREAD

**Issue by Estrelladelatorre1** [EstandaresDeCalidadSW23/vikingos-analyser#13]
Why is the plugins property empty in this configuration file?

**Comment by bcisneros** [comment]
@Estrelladelatorre1 could you please add more context to your question? Which file are you referring to?

**Comment by DanielDerma** [comment]
If you are referring to the tailwind.config.cjs file having an empty plugin array, it's because I didn't need to add any plugins to this project. There are many third-party plugins available, and you can learn more about them [here](https://tailwindcss.com/docs/plugins). However, they are not required for the functionality of this project.
